//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("IDO_Client.CustomNavigationPage.xaml", "CustomNavigationPage.xaml", typeof(global::IDO_Client.CustomNavigationPage))]

namespace IDO_Client {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("CustomNavigationPage.xaml")]
    public partial class CustomNavigationPage : global::Xamarin.Forms.NavigationPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(CustomNavigationPage));
        }
    }
}
